### ISSUE TITLE
Using x509 certificate chains to connect to IoTHub

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-iot-sdk-c#1055]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Ubuntu18.04 LTS
openssl 1.1.1 / mbedtls 2.8.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-05-16

**Protocol**

MQTT and MQTT/WS

**Describe the Bug**

Hi,

I'm trying to use the x509 CA signed method for devices to connect the IoThub and depending several variables sometimes the device don't connect. I correctly registered the Root certificate in the IoThub and generated intermediate and device certificates ( for device certificate the CN is the device id ). As the iothub contains only the root CA I had to put in the device both device and intermediate certificates in order to have the complete cert chain (which is normal). We tested with both RSA and EC certificates and observed the same results. The following table summarize the results:

| Cert   | TLS Layer | Protocol | using proxy | Connect?  | Trace ID           |
|--------|-----------|----------|-------------|---------------------------|--------------------|
| single | openssl   | MQTT     | NO          | YES                       | -                  |
| single | openssl   | MQTT     | YES         | YES                       | -                  |
| single | openssl   | MQTT/WS  | NO          | YES                       | -                  |
| single | openssl   | MQTT/WS  | YES         | YES                       | -                  |
| single | mbedtls   | MQTT     | NO          | NO                        | Trace timeout      |
| single | mbedtls   | MQTT     | YES         | NO                        | Trace timeout      |
| single | mbedtls   | MQTT/WS  | NO          | NO                        | Trace timeout      |
| single | mbedtls   | MQTT/WS  | YES         | NO                        | Trace WS+proxy     |
| chain  | openssl   | MQTT     | NO          | YES                       | -                  |
| chain  | openssl   | MQTT     | YES         | YES                       | -                  |
| chain  | openssl   | MQTT/WS  | NO          | NO                        | Trace unauthorized |
| chain  | openssl   | MQTT/WS  | YES         | NO                        | Trace FeedOption   |
| chain  | mbedtls   | MQTT     | NO          | NO                        | Trace timeout      |
| chain  | mbedtls   | MQTT     | YES         | NO                         | Trace timeout      |
| chain  | mbedtls   | MQTT/WS  | NO          | NO                        | Trace timeout      |
| chain  | mbedtls   | MQTT/WS  | YES         | NO                        | Trace WS+proxy     |

We tested all different configuration to see what is working and to isolate where the problem might comes from, but in the end we want to use mbedTLS with chained certificates and MQTT/WS behind a proxy.

Problems with mbedTLS may be related to issue #1040 

**[MCVE](https://stackoverflow.com/help/mcve)**

`iothub_ll_client_x509_sample` in iothub_client sample folder

**Console Logs**
*trace timeout*
```
Creating IoTHub handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Error: Time:Wed Jun 19 15:23:34 2019 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2358 mqtt_client timed out waiting for CONNACK
```

*trace WS+proxy*
```
Sending message 1 to IoTHub
Error: Time:Wed Jun 19 15:30:19 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:19 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_close Line:784 Invalid tlsio_state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:19 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:19 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Sending message 2 to IoTHub
Error: Time:Wed Jun 19 15:30:19 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Error: Time:Wed Jun 19 15:30:19 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:19 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_close Line:784 Invalid tlsio_state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Error: Time:Wed Jun 19 15:30:20 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:20 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_close Line:784 Invalid tlsio_state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:20 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:20 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:20 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Error: Time:Wed Jun 19 15:30:20 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Jun 19 15:30:20 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_close Line:784 Invalid tlsio_state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
```

*Trace unauthorized*
```
Creating IoTHub handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
-> 15:37:11 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.2%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 15:37:11 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Wed Jun 19 15:37:11 2019 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1728 Connection Not Accepted: 0x5: Not Authorized
-> 15:37:11 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.2%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 15:37:12 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Wed Jun 19 15:37:12 2019 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1728 Connection Not Accepted: 0x5: Not Authorized
-> 15:37:13 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.2%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 15:37:13 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Wed Jun 19 15:37:13 2019 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1728 Connection Not Accepted: 0x5: Not Authorized
```

*Trace FeedOption*
```
Creating IoTHub handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
-> 15:40:40 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.2%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 15:40:40 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1728 Connection Not Accepted: 0x5: Not Authorized
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:225 invalid arguments OPTIONHANDLER_HANDLE handle=0x55e5857c1190, void* destinationHandle=(nil)
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_setoption Line:1606 failed feeding options to underlying I/O instance
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option underlying_io_options
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_set_option Line:2063 OptionHandler_FeedOptions failed
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option uWSClientOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/wsio.c Func:wsio_setoption Line:676 unable to OptionHandler_FeedOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option WSIOOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Wed Jun 19 15:40:40 2019 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary Line:2108 Failed feeding existing options to new TLS instance.
```

**Comment by alexmrtn** [comment]
That would be really great to have the update matrix! The one above reflect the status of the `2019-05-16` version and the recent fixes may have solved few lines. Thanks!

**Comment by rafilho** [comment]
@alexmrtn, we should have addressed all of those in all the other fixes we had. Most of the fixes are already in master, except for the ones using proxy with mbedTLS (https://github.com/Azure/azure-iot-sdk-c/issues/1137). For this one, we have merged the fix into the c-shared-utilities, but we didn't integrate the latest submodule into iot-sdk-c. As Himanshu replied on that issues, it would be great if you could locally update your c-shared-utilities submodule to point to the latest commit/head on that branch and confirm if our fix worked for you. 

Please let us know if you still find issues in any of the combinations for this matrix. Thanks.

**Comment by alexmrtn** [comment]
Hi,

We tested the certificate chain connection with the last version of the SDK (2019-10-07).
Unfortunately, we still have issues to connect (see logs below)

This log is the result of the execution of what we want to achieve:
- Connection to the iothub with x509 certificates
- using elliptic curve based certificates
- having a chain of certificate, not only Root and leaf, but also one (or more) intermediate CA
- using mbedTLS layer
- behind our corporate proxy
- using the MQTT/WS transport protocol
- first Linux platform, Windows also eventually

```
Creating IoTHub handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
-> 14:35:05 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.6%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 14:35:05 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Fri Oct 18 14:35:05 2019 File:repo/deps/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1755 Connection Not Accepted: 0x5: Not Authorized
Error: Time:Fri Oct 18 14:35:05 2019 File:repo/deps/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_close Line:783 Invalid tlsio_state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
-> 14:35:07 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.6%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 14:35:07 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Fri Oct 18 14:35:07 2019 File:repo/deps/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1755 Connection Not Accepted: 0x5: Not Authorized
Error: Time:Fri Oct 18 14:35:07 2019 File:repo/deps/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_close Line:783 Invalid tlsio_state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Fri Oct 18 14:35:07 2019 File:repo/deps/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:225 invalid arguments OPTIONHANDLER_HANDLE handle=0x55ea721aaae0, void* destinationHandle=(nil)
Error: Time:Fri Oct 18 14:35:07 2019 File:repo/deps/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:186 unable to OptionHandler_FeedOptions
Error: Time:Fri Oct 18 14:35:07 2019 File:repo/deps/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Fri Oct 18 14:35:07 2019 File:repo/deps/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:186 unable to OptionHandler_FeedOptions
Error: Time:Fri Oct 18 14:35:07 2019 File:repo/deps/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
```

**Comment by danewalton** [comment]
Hi @alexmrtn are you able to give me some additional details into what your proxy is doing? I will look into a repro on my box.

**Comment by danewalton** [comment]
After some additional research it turns out IoT Hub does not currently support certificate chains with HTTP (which means web sockets as well).

**Comment by alexmrtn** [comment]
Hi, the proxy we use is not doing any specific action on the iothub connection, but we must use id in order to reach internet from our corporate network.

When you say "not currently support certificate chains", does that mean it will support it eventually?

**Comment by danewalton** [comment]
Yes it’s hard to give timelines but it is definitely a feature we’ve seen people asking for and is in plans for the future :)

**Comment by danewalton** [comment]
Going to go ahead and close this for now since it’s a current known service limitation.

**Comment by az-iot-builder-01** [comment]
@rafilho, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
