### ISSUE TITLE
Issues when building with MSVC and /permissive-

### ISSUE THREAD

**Issue by xiangfan-ms** [Azure/azure-iot-sdk-c#121]
Hi,
 I’m a developer in Visual C++ compiler team. We are currently doing daily RWC (Read World Code) testing which includes Azure sdk.

We are also working with internal partners and the community to fix source issues exposed by /permissive-.
The option isn’t finalized yet (we plan to add some large impact features into it in the incoming VS update), so we don’t suggest community to adopt it yet.
In the meantime, we want to address these source issues as early as possible so that the community can adopt it when it is finalized.

We discover some source issues when we build the library with /permissive-.

In serializer\tests\datapublisher_ut\datapublisher_ut.c, we see three occurrences of C2362:

datapublisher_ut.c(1306): error C2362: initialization of 'result' is skipped by 'goto next_fail'
datapublisher_ut.c(1405): error C2362: initialization of 'result' is skipped by 'goto next_fail'
datapublisher_ut.c(1511): error C2362: initialization of 'result' is skipped by 'goto next_fail'

The issue can be illustrated as follows:

	void f()
	{
		goto l;

		int i = 0;

	l:
		;
	}

It is explicitly disallowed by the C++ standard. VC will enforce this when /permissive- is used.

The suggested fix is to move the variable before goto. For example,

	void f()
	{
		int i;

		goto l;

		i = 0;

	l:
		;
	}

Can you fix the issue? Thanks!

**Comment by tameraw** [comment]
@xiangfan-ms - We added this to our backlog to address. We would also review a PR if you're able to provide one.

**Comment by xiangfan-ms** [comment]
BTW, the code is allowed in C (there are some subtle differences between C and C++). The reason it fails is because the project compiles the file as C++.

Is it expected that you compile a C99 source with /TP (which means compile as C++)?
Here is the command line:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /IF:\Azure_iot_sdk_c\src\serializer\..\parson /IF:\Azure_iot_sdk_c\src\serializer\inc /I"F:\Azure_iot_sdk_c\src\c-utility\inc" /IF:\Azure_iot_sdk_c\src\iothub_client\inc /I"F:\Azure_iot_sdk_c\src\c-utility\testtools\micromock\inc" /I"F:\Azure_iot_sdk_c\src\c-utility\testtools\umock-c\inc" /I"F:\Azure_iot_sdk_c\src\c-utility\testtools\testrunner\inc" /I"F:\Azure_iot_sdk_c\src\c-utility\testtools\ctest\inc" /I"F:\Azure_iot_sdk_c\src\c-utility\src" /I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\UnitTest\include" /nologo /W4 /WX /O2 /Ob2 /Oy- /D CPPUNITTEST_SYMBOL=some_symbol_for_cppunittest_1 /D WIN32 /D _WINDOWS /D NDEBUG /D CPP_UNITTEST /D _CRT_SECURE_NO_WARNINGS /D ARCHITECTURE_x86=1 /D GB_MEASURE_MEMORY_FOR_THIS /D GB_DEBUG_ALLOC /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"datapublisher_ut_testsonly_lib.dir\Release\\" /Fd"datapublisher_ut_testsonly_lib.dir\Release\datapublisher_ut_testsonly_lib.pdb" /Gd **/TP** /wd4232 /analyze- /errorReport:queue **F:\Azure_iot_sdk_c\src\serializer\tests\datapublisher_ut\datapublisher_ut.c**

**Comment by xiangfan-ms** [comment]
There is another issue in 'c-utility\testtools\umock-c\tests\umocktypes_charptr_ut\umocktypes_charptr_ut.c'.

It has something like,

char *input = "";

This is not allowed in C++ because string literal '""' has type 'const char [1]'.
You can fix it by using 'const char *'. And then you no longer need C-style cast below:

(const char **)&input

->

&input

**Comment by jebrando** [comment]
These two issues are fixed and will be checked in

**Comment by PhoebeHui** [comment]
The issue in 'c-utility\testtools\umock-c\tests\umocktypes_charptr_ut\umocktypes_charptr_ut.c' fixed.

But another one looks not, does all the fixes checked in? I still see the failures with latest revision 'eda552b'
        D:\Azure_iot_sdk_c\src\serializer\tests\datapublisher_ut\datapublisher_ut.c(1305): error C2362: initialization of 'result' is skipped by 'goto next_fail' [D:\Azure_iot_sdk_c\build_x86\serializer\tests\datapublisher_ut\datapublisher_ut_testsonly_lib.vcxproj]

         D:\Azure_iot_sdk_c\src\serializer\tests\datapublisher_ut\datapublisher_ut.c(1404): error C2362: initialization of 'result' is skipped by 'goto next_fail' [D:\Azure_iot_sdk_c\build_x86\serializer\tests\datapublisher_ut\datapublisher_ut_testsonly_lib.vcxproj]
         D:\Azure_iot_sdk_c\src\serializer\tests\datapublisher_ut\datapublisher_ut.c(1510): error C2362: initialization of 'result' is skipped by 'goto next_fail' [D:\Azure_iot_sdk_c\build_x86\serializer\tests\datapublisher_ut\datapublisher_ut_testsonly_lib.vcxproj]
