### ISSUE TITLE
Link to API documentation broken

### ISSUE THREAD

**Issue by ollyw** [Azure/azure-iot-sdk-c#133]
When navigating the README.md on Github, the link to the API documentation returns a 404. The target of the link is https://azure.github.io/azure-iot-sdks/c/api_reference/index.html, but it seems the site has been rearranged.

I would put in a pull request, but I can't seem to actually find the API docs on the site, but I did try to find it. I followed a link to the new site (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide), clicked Documentation, then  'Reference' on the left hand pane, and then Azure IoT SDKs link, which also gave a 404.

It would be useful to have all the dead links fixed

**Comment by tameraw** [comment]
@ollyw - Thanks for reporting those broken links. They should be fixed now.

**Comment by ollyw** [comment]
@tameraw Thanks for fixing the link in the readme. The second link from the Reference in the devguide is still broken though. Perhaps the fix has not been deployed?

**Comment by tameraw** [comment]
@ollyw - Can you check if the link is still broken?
When I go to the site https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide
Then click the link to the C SDK under Reference (on the left hand side) I get routed to the correct API page. I wanted to confirm with you if we might've still missed a dead link. Thanks.

**Comment by ollyw** [comment]
@tameraw this is *almost* fixed: the link now works, but the caption displays 'C\&nbsp;device SDK'. It appears that there is a non-breaking space in the caption. I imagine that there is a javascript lib rendering the tree, and it doesn't take into account HMTL escape characters. The question is as to whether the NBSP is needed in the first place. I tested this in Firefox and Chrome.

**Comment by ewertons** [comment]
Hi @ollyw , are you still experiencing this issue?
I opened the [link](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide) and couldn't find the broken caption you mentioned.

**Comment by ollyw** [comment]
@ewertons the problem has gone. Great news :+1:

**Comment by ewertons** [comment]
Thanks @ollyw ! 
Please let us know if you see anything else wrong.
Thanks for contributing the Azure IoT SDKs
